### ISSUE TITLE
スプラッシュスクリーンを非表示にする

### ISSUE THREAD

**Issue by yuukis** [cosmoway/furufuru-ball-ios#23]
タイトル画面（=ロビー画面）もあるので、スプラッシュスクリーンを表示にする

![img_0008](https://cloud.githubusercontent.com/assets/2931035/9377368/4966ff6a-4753-11e5-8df4-d50fb177e418.PNG)

**Comment by yuusukex1** [comment]
#20150820_repairにてスプラッシュ画面を非表示にしました

**Comment by yuukis** [comment]
コミット 757dee5 で非表示になったことを確認しました。OKです
