### ISSUE TITLE
ゲームを開始した時でもヘルプ画面がでてしまう

### ISSUE THREAD

**Issue by takerusakano** [cosmoway/furufuru-ball-ios#25]
ヘルプのアイコンは消えるが押せてしまうのでヘルプの画面がどこでも出てしまいます。
ヘルプのアイコンが消えたら押せなくなるように修正しましょう。
![img_0017](https://cloud.githubusercontent.com/assets/11749870/9378246/d788f38c-475a-11e5-91d2-e62db135dcac.PNG)

**Comment by takerusakano** [comment]
nodesとfpsも表示させないようにしましょう。

**Comment by yuusukex1** [comment]
#20150820_pepiar_helpにて修正しました

**Comment by yuukis** [comment]
確認しました。OKです！
