### ISSUE TITLE
nodesとfpsの表示されている。

### ISSUE THREAD

**Issue by takerusakano** [cosmoway/furufuru-ball-ios#26]
nodesとfpsの表示はいらないので非表示にしましょう。
![img_0018](https://cloud.githubusercontent.com/assets/11749870/9378560/631b5e74-475d-11e5-9336-38d552b670ed.PNG)

**Comment by yuusukex1** [comment]
#20150820_pepiar_helpにて非表示にしました

**Comment by yuukis** [comment]
確認しました。master にマージします。
