### ISSUE TITLE
アプリのタイトル（at ホーム画面）

### ISSUE THREAD

**Issue by yuukis** [cosmoway/furufuru-ball-ios#28]
ホーム画面上のアイコンには **furufuru-ball-ios** と表示されていますが、ここは **ふるふるボール** と表示させた方が良さそうな気がします。

![img_0009](https://cloud.githubusercontent.com/assets/2931035/9378970/b589b1ee-4760-11e5-82b9-c076a7391851.PNG)

**Comment by takerusakano** [comment]
#20150820_app_nameというブランチにてアプリのタイトル変更しました。

**Comment by yuukis** [comment]
**ふるふるボール** に変わったことを確認しました。
