### ISSUE TITLE
ゲームスタート後に途中で join できないよう、グループのcountを受け取る。

### ISSUE THREAD

**Issue by ryujyu** [cosmoway/furufuru-ball-ios#30]
count を受け取るよう変更する

**Comment by yuukis** [comment]
ありがとうございます。
サーバ側のバグのようです。
サーバ側を改修します。

**複数の端末で同時にスタートを押下すると、複数のボールを返してしまう**
https://github.com/cosmoway/furufuru-ball-server/issues/1
